### ISSUE TITLE
dis nigga really used 3arthh4ck base 🤦🏾‍♂️

### ISSUE THREAD

**Issue by legendaryhvher** [sexmaster-cc/sexmastercc#2]

**Comment by pycnocarpa** [comment]
show me whats earthhack

**Comment by legendaryhvher** [comment]
> show me whats earthhack

Main class = NAME: 3ARTHH4CK

**Comment by pycnocarpa** [comment]
cringe

**Comment by legendaryhvher** [comment]
> cringe

ok lets be fR.. Entire client 3arthh4ck

**Comment by pycnocarpa** [comment]
lets be fr talking like that stopped being funny last year + its not earthhack just cuz u cant paste it
