### ISSUE TITLE
Rat´

### ISSUE THREAD

**Issue by rljq-ai** [sexmaster-cc/sexmastercc#6]
RAT

**Comment by crystalpvpnn** [comment]
Lol true I got blue screened because of this

**Comment by pycnocarpa** [comment]
can u point out where the rat is so i can make the cleaned version

**Comment by rljq-ai** [comment]
> can u point out where the rat is so i can make the cleaned version

**Comment by rljq-ai** [comment]
> can u point out where the rat is so i can make the cleaned version

![image](https://github.com/sexmaster-cc/sexmastercc/assets/105388194/bdbafbfe-24a9-43f2-bb40-3638bccbd938)
