### ISSUE TITLE
Rat!!!!

### ISSUE THREAD

**Issue by rljq-ai** [sexmaster-cc/sexmastercc#7]
Rat 
![image (4)](https://github.com/sexmaster-cc/sexmastercc/assets/105388194/44134595-1edc-4745-b061-5bf681ed3960)

**Comment by transfemangel** [comment]
Cleaning rn

**Comment by pycnocarpa** [comment]
damn u got me

**Comment by dkj2u23o** [comment]
invalid webhook url
